server:
  error:
    include-stacktrace: never

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
#        include: "*"
        include: info, health, metrics, prometheus

info:
  app: Spring Anime CRUD
  website: https://anime.crud
  github: https://github.com/Fael123Programming/spring-anime-crud
